"""
Schemas package - Pydantic models for request/response validation
"""

from .user_schema import (
    UserCreate,
    UserUpdate,
    UserRead,
    UserLogin,
    UserRegister,
    UserOTPVerify,
    UserChangePassword,
    TokenResponse,
    OrganizationBase,
    OrganizationCreate,
    OrganizationRead,
    OrganizationMemberBase,
    OrganizationMemberCreate,
    OrganizationMemberRead,
)

from .post_schema import (
    PostCreate,
    PostUpdate,
    PostRead,
    PostDetailRead,
    PostListRead,
    PostProductCreate,
    PostProductRead,
    PostImageCreate,
    PostImageRead,
    PostFilter,
    PostApprovalAction,
)

from .campaign_schema import (
    CampaignCreate,
    CampaignUpdate,
    CampaignRead,
    CampaignDetailRead,
    CampaignListRead,
    CampaignFilter,
    CampaignApprovalAction,
)

from .transaction_schema import (
    TransactionCreate,
    TransactionRead,
    TransactionListRead,
    TransactionFilter,
    TransactionStatusUpdate,
    SettingsCreate,
    SettingsUpdate,
    SettingsRead,
    PaymentInitiate,
    PaymentConfirm,
    CartItemCreate,
    CartItemRead,
    CartRead,
    ReturnRequestCreate,
    ReturnRequestRead,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserUpdate",
    "UserRead",
    "UserLogin",
    "UserRegister",
    "UserOTPVerify",
    "UserChangePassword",
    "TokenResponse",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationRead",
    "OrganizationMemberBase",
    "OrganizationMemberCreate",
    "OrganizationMemberRead",
    # Post schemas
    "PostCreate",
    "PostUpdate",
    "PostRead",
    "PostDetailRead",
    "PostListRead",
    "PostProductCreate",
    "PostProductRead",
    "PostImageCreate",
    "PostImageRead",
    "PostFilter",
    "PostApprovalAction",
    # Campaign schemas
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignRead",
    "CampaignDetailRead",
    "CampaignListRead",
    "CampaignFilter",
    "CampaignApprovalAction",
    # Transaction schemas
    "TransactionCreate",
    "TransactionRead",
    "TransactionListRead",
    "TransactionFilter",
    "TransactionStatusUpdate",
    "SettingsCreate",
    "SettingsUpdate",
    "SettingsRead",
    "PaymentInitiate",
    "PaymentConfirm",
    "CartItemCreate",
    "CartItemRead",
    "CartRead",
    "ReturnRequestCreate",
    "ReturnRequestRead",
]
